import Head from "next/head"
import styles from "@/styles/Home.module.css"
import Button from "@mui/material/Button"
import { AppBar, Box, Card, CssBaseline, IconButton, Stack, Toolbar } from "@mui/material"
import MenuIcon from "@mui/icons-material/Menu"
import Typography from "@mui/material/Typography"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Box sx={{ display: "flex" }}>
                    <CssBaseline />

                    <AppBar component="nav">
                        <Toolbar>
                            <IconButton
                                size="large"
                                edge="start"
                                color="inherit"
                                aria-label="menu"
                                sx={{ mr: 2 }}
                            >
                                <MenuIcon />
                            </IconButton>
                            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                                News
                            </Typography>
                            <Button color="inherit">Start</Button>
                        </Toolbar>
                    </AppBar>
                    <Box component={"main"}>
                        <Stack direction={"row"}>
                            <Stack direction={"column"}>
                                <Card>Card 1</Card>
                                <Card>Card 2</Card>
                                <Card>Card 3</Card>
                            </Stack>

                            <Stack direction={"column"}>
                                <Card>Card 1</Card>
                                <Card>Card 2</Card>
                                <Card>Card 3</Card>
                            </Stack>

                            <Stack direction={"column"}>
                                <Card>Card 1</Card>
                                <Card>Card 2</Card>
                                <Card>Card 3</Card>
                            </Stack>
                        </Stack>

                        <Button variant="contained">Hello World</Button>
                    </Box>
                </Box>
            </main>
        </>
    )
}
