name: deploy-to-cloud-run

on: [workflow_dispatch, workflow_call]

env:
    GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
    GCP_REGION: ${{ vars.GCP_REGION }}
    REPO_NAME: ${{ vars.REPO_NAME }}
    IMAGE_NAME: "gcr.io/${{ secrets.GCP_PROJECT }}/${{ vars.REPO_NAME }}:$GITHUB_SHA"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: google-github-actions/auth@v1
              with:
                  workload_identity_provider: ${{ secrets.GCP_SA_KEY }}
                  service_account: ${{ secrets.GCP_SA_EMAIL }}
    
            - name: Enable the necessary APIs and enable docker auth
              run: |-
                  gcloud services enable containerregistry.googleapis.com
                  gcloud services enable run.googleapis.com
                  gcloud --quiet auth configure-docker

            - name: Build and tag image
              run: |-
                  docker build . --tag "gcr.io/$GCP_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
                  
            - name: Push image to GCR
              run: |-
                  docker push gcr.io/$GCP_PROJECT/$REPO_NAME:$GITHUB_SHA
                  
            - id: 'deploy'
              uses: 'google-github-actions/deploy-cloudrun@v1'
              with: 
                  service: 'hello-cloud-run'
                  image: 'gcr.io/$GCP_PROJECT_ID/$REPO_NAME:$GITHUB_SHA'
