name: deploy-to-cloud-run

on: [workflow_dispatch, workflow_call]



env:
    GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
    GCP_REGION: ${{ vars.GCP_REGION }}
    REPO_NAME: ${{ vars.REPO_NAME }}
    IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/${{ vars.REPO_NAME }}:${{ vars.GITHUB_SHA }}
    GCP_SERVICE_NAME: "kanban-full-stack"

jobs:
    build-and-deploy:
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
                  service_account: ${{ secrets.GCP_SA_EMAIL }}
    
            - name: Enable the necessary APIs and enable docker auth
              run: |-
                  gcloud services enable containerregistry.googleapis.com
                  gcloud services enable run.googleapis.com
                  gcloud --quiet auth configure-docker

            - name: Build and tag image
              run: |-
                  echo $IMAGE_NAME
                  docker build . --tag "${{ env.IMAGE_NAME }}"
