name: deploy-to-cloud-run

on: [workflow_dispatch, workflow_call]



env:
    GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
    GCP_REGION: ${{ vars.GCP_REGION }}
    REPO_NAME: ${{ vars.REPO_NAME }}
    GCP_SERVICE_NAME: "kanban-full-stack"

jobs:
    build-and-deploy:
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: set IMAGE_NAME env value
              run: echo "IMAGE_NAME=${echo gcr.io/$GCP_PROJECT/$REPO_NAME:$GITHUB_SHA}" >> $GITHUB_ENV
            - run: echo $IMAGE_NAME
