name: cloud-run

on: [workflow_dispatch]

env:
    GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_NAME }}
    GCP_REGION: ${{ vars.GCP_REGION }}
    REPO_NAME: ${{ vars.REPO_NAME }}

jobs:
    build-and-deploy:
        name: Prepare cloud-run deployment tools
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # This step is where our service account will be authenticated
            - uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: ${{ secrets.GCP_PROJECT_NAME }}
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
                  service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

            - name: Enable the necessary APIs and enable docker auth
              run: |-
                  gcloud services enable containerregistry.googleapis.com
                  gcloud services enable run.googleapis.com
                  gcloud --quiet auth configure-docker
            - name: Build and tag image
              run: |-
                  docker build . --tag "gcr.io/$GCP_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
            - name: Push image to GCR
              run: |-
                  docker push gcr.io/$GCP_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
            - name: Deploy
              run: |-
                  gcloud components install beta --quiet
                  gcloud beta run deploy $REPO_NAME --image gcr.io/$GCP_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
                    --project $GCP_PROJECT_ID \
                    --platform managed \
                    --region $GCP_REGION \
                    --allow-unauthenticated \
                    --quiet
