name: release

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - master

jobs:
    call-inspect-code:
        uses: hafemeister/kanban-full-stack/.github/workflows/inspect-code.yaml@main

    call-unit-test-code:
        uses: hafemeister/kanban-full-stack/.github/workflows/unit-test-code.yaml@main

    call-deploy-to-cloud-run:
        permissions:
            contents: "read"
            id-token: "write"
        secrets: inherit
        needs:
            - call-inspect-code
            - call-unit-test-code
        uses: hafemeister/kanban-full-stack/.github/workflows/deploy-to-cloud-run.yaml@main
