name: unit-test-code

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches:
            - "features**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "npm"
            - name: test
              run: |
                  npm ci
                  npm run test
